# -*- coding: utf-8 -*-
"""custom cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cEkWtSCaIjEkzuKhGEBFSi2XAbL60TpM
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import time

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import warnings
warnings.filterwarnings("ignore")

import tensorflow as tf
print(tf.__version__)

from tensorflow.keras import datasets, layers, models
from keras import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import SGD,Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.applications import VGG19,Xception
from tensorflow.keras.layers import Input,Flatten,Dense,BatchNormalization,Activation,Dropout,GlobalAveragePooling2D,MaxPooling2D,RandomFlip,RandomZoom,RandomRotation

from keras.datasets import cifar10

print(tf.config.list_physical_devices('GPU'))

(x_train, y_train), (x_test_full, y_test_full) = cifar10.load_data()

split = len(x_test_full) // 2
x_val,  y_val  = x_test_full[:split],  y_test_full[:split] #Validation
x_test, y_test = x_test_full[split:],  y_test_full[split:] #Test

print("Train set     :", x_train.shape, y_train.shape)
print("Validation set:", x_val.shape,   y_val.shape)
print("Test set      :", x_test.shape,  y_test.shape)

y_train_cat = to_categorical(y_train, 10)
y_val_cat   = to_categorical(y_val,   10)
y_test_cat  = to_categorical(y_test,  10)

CLASS_NAMES = ['airplane','automobile','bird','cat','deer',
               'dog','frog','horse','ship','truck']

model = models.Sequential()

model.add(layers.Input(shape=(32, 32, 3)))


model.add(layers.Rescaling(1./255))

model.add(layers.RandomFlip("horizontal"))
model.add(layers.RandomRotation(0.1))
model.add(layers.RandomZoom(0.1))

model.add(layers.Conv2D(32, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.compile(
    optimizer=tf.keras.optimizers.Adam(0.0009),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

#model.compile(optimizer=tf.keras.optimizers.Adam(0.0011), loss='categorical_crossentropy', metrics=['accuracy'])

lr_reduce  = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1)
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

cnn_start = time.time()
history_cnn = model.fit(
    x_train, y_train_cat,
    validation_data=(x_val, y_val_cat),
    epochs=26,
    callbacks=[lr_reduce, early_stop],
    verbose=1
)
cnn_total_time = time.time() - cnn_start

cnn_loss, cnn_acc = model.evaluate(x_test, y_test_cat, verbose=0)
print(f"Custom CNN Test Accuracy: {cnn_acc:.4f}")

def plot_history(history, title=""):
    fig, axes = plt.subplots(1, 2, figsize=(14, 4))
    df = pd.DataFrame(history.history)

    axes[0].plot(df['loss'], label='Train Loss')
    axes[0].plot(df['val_loss'], label='Val Loss')
    axes[0].set_title(f'{title} — Loss')
    axes[0].legend()

    axes[1].plot(df['accuracy'], label='Train Acc')
    axes[1].plot(df['val_accuracy'], label='Val Acc')
    axes[1].set_title(f'{title} — Accuracy')
    axes[1].legend()

    plt.tight_layout()
    plt.show()

class_names=['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

plot_history(history_cnn, title="Custom CNN")


def plot_confusion_matrix(model, x, y_true_cat, title=""):
    preds  = model.predict(x)
    y_pred = np.argmax(preds, axis=1)
    y_true = np.argmax(y_true_cat, axis=1)
    cm = tf.math.confusion_matrix(y_true, y_pred).numpy()

    plt.figure(figsize=(12, 9))
    sns.heatmap(cm, annot=True, fmt='g',
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
    plt.title(f'Confusion Matrix — {title}')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    plt.show()

plot_confusion_matrix(model, x_test, y_test_cat,
                      title="Custom CNN")