# -*- coding: utf-8 -*-
"""Xception.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCtMVL4AwK4r4q4z8V9OBb40bVICp9nM
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import time

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import warnings
warnings.filterwarnings("ignore")

import tensorflow as tf
print(tf.__version__)

from keras import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import SGD,Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.applications import VGG19,Xception
from tensorflow.keras.layers import Input,Flatten,Dense,BatchNormalization,Activation,Dropout,GlobalAveragePooling2D,MaxPooling2D,RandomFlip,RandomZoom,RandomRotation

from keras.datasets import cifar10

(x_train, y_train), (x_test_full, y_test_full) = cifar10.load_data()

split = len(x_test_full) // 2
x_val,  y_val  = x_test_full[:split],  y_test_full[:split]
x_test, y_test = x_test_full[split:],  y_test_full[split:]

print("Train set     :", x_train.shape, y_train.shape)
print("Validation set:", x_val.shape,   y_val.shape)
print("Test set      :", x_test.shape,  y_test.shape)

y_train_cat = to_categorical(y_train, 10)
y_val_cat   = to_categorical(y_val,   10)
y_test_cat  = to_categorical(y_test,  10)

CLASS_NAMES = ['airplane','automobile','bird','cat','deer',
               'dog','frog','horse','ship','truck']

print("Pre-resizing images to 75x75 (one-time cost)...")
x_train_resized = tf.image.resize(x_train, (75, 75)).numpy()
x_val_resized   = tf.image.resize(x_val,   (75, 75)).numpy()
x_test_resized  = tf.image.resize(x_test,  (75, 75)).numpy()
print("Done:", x_train_resized.shape)

SUBSET = 10000

x_train_resized = x_train_resized[:SUBSET]
y_train_cat     = y_train_cat[:SUBSET]

base_model = Xception(include_top=False, weights='imagenet', input_shape=(75,75,3))

base_model.trainable = False

base_model.summary()

data_augmentation = Sequential(
    [RandomFlip("horizontal"),
     RandomRotation(0.1),
     RandomZoom(0.1)]
)

inputs = tf.keras.Input(shape=(75, 75, 3))

x = data_augmentation(inputs)
x = tf.keras.applications.xception.preprocess_input(x)
x = base_model(x, training=False)
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
outputs = Dense(10, activation='softmax')(x)

model = tf.keras.Model(inputs, outputs, name="Xception_FineTuned")
model.summary()

#model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.compile(optimizer=tf.keras.optimizers.Adam(0.0011), loss='categorical_crossentropy', metrics=['accuracy'])

lr_reduce  = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1)
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

print("\n=== Phase 1 ===")
xc_start = time.time()
history_xc1 = model.fit(
    x_train_resized, y_train_cat,
    validation_data=(x_val_resized, y_val_cat),
    epochs=20,
    callbacks=[lr_reduce, early_stop],
    verbose=1
)
xc_phase1_time = time.time() - xc_start

lr_reduce_2  = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1)
early_stop_2 = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

base_model.trainable = True

model.compile(optimizer=tf.keras.optimizers.Adam(1e-5), loss='categorical_crossentropy', metrics=['accuracy'])

xc_ft_start = time.time()

import gc
gc.collect()

history_xc2 = model.fit(
    x_train_resized, y_train_cat,
    validation_data=(x_val_resized, y_val_cat),
    epochs=10,
    callbacks=[lr_reduce_2, early_stop_2],
    verbose=1
)

xc_total_time = (time.time() - xc_ft_start) + xc_phase1_time

xc_loss, xc_acc = model.evaluate(
    x_test_resized, y_test_cat, verbose=0
)
print(f"\nXception Test Accuracy: {xc_acc:.4f}")

def plot_history(history, title=""):
    fig, axes = plt.subplots(1, 2, figsize=(14, 4))
    df = pd.DataFrame(history.history)

    axes[0].plot(df['loss'], label='Train Loss')
    axes[0].plot(df['val_loss'], label='Val Loss')
    axes[0].set_title(f'{title} — Loss')
    axes[0].legend()

    axes[1].plot(df['accuracy'], label='Train Acc')
    axes[1].plot(df['val_accuracy'], label='Val Acc')
    axes[1].set_title(f'{title} — Accuracy')
    axes[1].legend()

    plt.tight_layout()
    plt.show()

combined_xc_history = {
    k: history_xc1.history[k] + history_xc2.history[k]
    for k in history_xc1.history
}

class_names=['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

plot_history(type('obj', (object,), {'history': combined_xc_history})(),
             title="Xception")


def plot_confusion_matrix(model, x, y_true_cat, title=""):
    preds  = model.predict(x)
    y_pred = np.argmax(preds, axis=1)
    y_true = np.argmax(y_true_cat, axis=1)
    cm = tf.math.confusion_matrix(y_true, y_pred).numpy()

    plt.figure(figsize=(12, 9))
    sns.heatmap(cm, annot=True, fmt='g',
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
    plt.title(f'Confusion Matrix — {title}')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    plt.show()

plot_confusion_matrix(model, x_test_resized, y_test_cat,
                      title="Xception")